#!/usr/bin/env python3
# Copyright (c) 2025-2026 CipherFlow (Shenzhen) Co., Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

"""Plot memory usage from CSV files generated by MemoryMonitor / GpuMemoryMonitor.

CPU CSV columns : elapsed_ms, rss_kb, rss_gb
GPU CSV columns : elapsed_ms, used_gb, pool_gb

Mode is auto-detected from the CSV header unless --mode is specified.
"""

import sys
import csv
import argparse


def detect_mode(fieldnames):
    if 'used_gb' in fieldnames:
        return 'gpu'
    if 'rss_gb' in fieldnames:
        return 'cpu'
    print('ERROR: cannot detect mode from CSV header:', fieldnames)
    sys.exit(1)


def load_cpu(path):
    elapsed, rss_gb = [], []
    with open(path) as f:
        for row in csv.DictReader(f):
            elapsed.append(float(row['elapsed_ms']) / 1000.0)
            rss_gb.append(float(row['rss_gb']))
    return elapsed, rss_gb


def load_gpu(path):
    elapsed, used_gb, pool_gb = [], [], []
    with open(path) as f:
        for row in csv.DictReader(f):
            elapsed.append(float(row['elapsed_ms']) / 1000.0)
            used_gb.append(float(row['used_gb']))
            pool_gb.append(float(row['pool_gb']))
    return elapsed, used_gb, pool_gb


def ascii_chart(elapsed, values, label):
    width, height = 80, 20
    min_v, max_v = min(values), max(values)
    span = max_v - min_v or 1
    chart = [[' '] * width for _ in range(height)]
    n = len(elapsed)
    for i, v in enumerate(values):
        x = int(i / n * (width - 1))
        y = int((v - min_v) / span * (height - 1))
        chart[height - 1 - y][x] = '*'
    print(f'  {label}  [{min_v:.2f} .. {max_v:.2f} GB]')
    for row in chart:
        print('  |' + ''.join(row))
    print('  +' + '-' * width)
    print(f'  0 s {"":<{width - 6}} {elapsed[-1]:.1f} s')


def plot_cpu(elapsed, rss_gb, out):
    peak_rss = max(rss_gb)
    avg_rss = sum(rss_gb) / len(rss_gb)
    rss_at_start = rss_gb[0]
    peak_delta = peak_rss - rss_at_start

    try:
        import matplotlib

        matplotlib.use('Agg')
        import matplotlib.pyplot as plt

        fig, ax = plt.subplots(figsize=(12, 5))
        ax.plot(elapsed, rss_gb, linewidth=1.2, color='#2196F3', label='RSS (GB)')
        ax.axhline(peak_rss, color='#F44336', linestyle='--', linewidth=1, label=f'Peak RSS {peak_rss:.2f} GB')
        ax.axhline(avg_rss, color='#FF9800', linestyle=':', linewidth=1, label=f'Avg RSS  {avg_rss:.2f} GB')
        ax.axhline(
            rss_at_start, color='#4CAF50', linestyle='-.', linewidth=1, label=f'RSS at start {rss_at_start:.2f} GB'
        )
        ax.fill_between(elapsed, rss_gb, alpha=0.15, color='#2196F3')
        ax.set_xlabel('Time (s)')
        ax.set_ylabel('Memory (GB)')
        ax.set_title('CPU Inference Memory Usage')
        ax.legend(loc='upper left')
        ax.grid(True, alpha=0.3)
        plt.tight_layout()
        plt.savefig(out, dpi=150)
        print(f'Saved plot to {out}')
    except ImportError:
        print('matplotlib not available, printing ASCII chart.\n')
        ascii_chart(elapsed, rss_gb, 'RSS Memory (GB)')
        print(f'\n  Peak RSS: {peak_rss:.2f} GB   Avg: {avg_rss:.2f} GB   Duration: {elapsed[-1]:.1f} s')

    print(f'\nSummary:')
    print(f'  Samples      : {len(elapsed)}')
    print(f'  Duration     : {elapsed[-1]:.2f} s')
    print(f'  RSS at start : {rss_at_start:.2f} GB')
    print(f'  Peak RSS     : {peak_rss:.2f} GB')
    print(f'  Peak Delta   : {peak_delta:.2f} GB  [peak - rss_at_start]')
    print(f'  Avg  RSS     : {avg_rss:.2f} GB')
    print(f'  Final RSS    : {rss_gb[-1]:.2f} GB')


def plot_gpu(elapsed, used_gb, pool_gb, out):
    peak_used = max(used_gb)
    avg_used = sum(used_gb) / len(used_gb)
    pool = pool_gb[0] if pool_gb else 0.0

    try:
        import matplotlib

        matplotlib.use('Agg')
        import matplotlib.pyplot as plt

        fig, ax = plt.subplots(figsize=(12, 5))
        ax.plot(elapsed, used_gb, linewidth=1.2, color='#4CAF50', label='Used VRAM (GB)')
        if pool > 0:
            ax.axhline(pool, color='#607D8B', linestyle='-.', linewidth=1, label=f'Pool Capacity {pool:.2f} GB')
        ax.axhline(peak_used, color='#F44336', linestyle='--', linewidth=1, label=f'Peak {peak_used:.2f} GB')
        ax.axhline(avg_used, color='#FF9800', linestyle=':', linewidth=1, label=f'Avg  {avg_used:.2f} GB')
        ax.fill_between(elapsed, used_gb, alpha=0.15, color='#4CAF50')
        ax.set_xlabel('Time (s)')
        ax.set_ylabel('VRAM (GB)')
        ax.set_title('GPU Inference VRAM Usage')
        ax.legend(loc='upper left')
        ax.grid(True, alpha=0.3)
        plt.tight_layout()
        plt.savefig(out, dpi=150)
        print(f'Saved plot to {out}')
    except ImportError:
        print('matplotlib not available, printing ASCII chart.\n')
        ascii_chart(elapsed, used_gb, 'Used VRAM (GB)')
        print(f'\n  Peak: {peak_used:.2f} GB   Avg: {avg_used:.2f} GB   Duration: {elapsed[-1]:.1f} s')

    print(f'\nSummary:')
    print(f'  Samples       : {len(elapsed)}')
    print(f'  Duration      : {elapsed[-1]:.2f} s')
    print(f'  Pool Capacity : {pool:.2f} GB')
    print(
        f'  Peak Used     : {peak_used:.2f} GB  ({100 * peak_used / pool:.1f}%)'
        if pool
        else f'  Peak Used     : {peak_used:.2f} GB'
    )
    print(f'  Avg  Used     : {avg_used:.2f} GB')
    print(f'  Final Used    : {used_gb[-1]:.2f} GB')


def main():
    parser = argparse.ArgumentParser(description='Plot CPU/GPU memory usage over time')
    parser.add_argument('csv', nargs='?', default='mem_usage_cpu.csv', help='Input CSV file')
    parser.add_argument('--out', default=None, help='Output image file (default: <csv>.png)')
    parser.add_argument(
        '--mode',
        choices=['cpu', 'gpu'],
        default=None,
        help='Force cpu or gpu mode (auto-detected from CSV header by default)',
    )
    args = parser.parse_args()

    # Auto-detect mode from CSV header
    with open(args.csv) as f:
        fieldnames = csv.DictReader(f).fieldnames or []
    mode = args.mode or detect_mode(fieldnames)

    out = args.out or args.csv.rsplit('.', 1)[0] + '.png'

    if mode == 'cpu':
        elapsed, rss_gb = load_cpu(args.csv)
        if not elapsed:
            print('No data found in CSV.')
            sys.exit(1)
        plot_cpu(elapsed, rss_gb, out)
    else:
        elapsed, used_gb, pool_gb = load_gpu(args.csv)
        if not elapsed:
            print('No data found in CSV.')
            sys.exit(1)
        plot_gpu(elapsed, used_gb, pool_gb, out)


if __name__ == '__main__':
    main()
